groups/urls.py
from django.urls import path, include
from . import views
app_name='groups'

urlpatterns = [
	path('',views.ListGroups.as_view(),name='all'),
	path('new/',views.CreateGroup.as_view(),name='create'),
	path('posts/in/(?P<slug>[-\w]+)/',views.SingleGroup.as_view(),name='single'),
	path('join/(?P<slug>[-\w]+)/',views.JoinGroup.as_view(),name='join'),
	path('leave/(?P<slug>[-\w]+)/',views.LeaveGroup.as_view(),name='leave')
]

posts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings # new
from django.conf.urls.static import static # new

app_name = 'posts'


urlpatterns = [
	path('',views.PostList.as_view(),name='all'),
	path('new/',views.CreatePost.as_view(),name='create'),
	path('by/(?P<username>[-\w]+)/',views.UserPosts.as_view(),name='for_user'),
	path('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(),name='single'),
	path('delete/(?P<pk>\d+)/',views.DeletePost.as_view(),name='delete'),
	path('update/(?P<pk>\d+)/',views.UpdatePost.as_view(),name='update')

]


# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import misaka
from django.contrib.auth import get_user_model
from django import template

User = get_user_model()
register = template.Library()

class Group(models.Model):
	name = models.CharField(max_length=255,unique=True)
	slug = models.SlugField(allow_unicode=True,unique=True)#slug field create URl
	description = models.TextField(blank=True,default='')
	description_html = models.TextField(editable=False,blank=True,default='')
	members =  models.ManyToManyField(User,through='GroupMember')

	def __str__(self):
		return self.name

	def save(self,*args,**kwargs):
		self.slug = slugify(self.name)
		self.description_html = misaka.html(self.description)
		super().save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('groups:single',kwargs={'slug':self.slug})

	class Meta:
		ordering = ['name']


class GroupMember(models.Model):
	"""docstring for GroupMember"""

	group = models.ForeignKey(Group,related_name='memeberships',on_delete=models.CASCADE)
	user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

	def __str__(self):
		return self.user.username

	class Meta:
		unique_together= ('group','user')

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember
from django.contrib import messages

# Create your views here.
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    """docstring forSingleGroup."""
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self, *args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        #Like find or fail

        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,' WARNING: already a member ')
        else:
            messages.success(self.request,' You are now a member ')

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self, *args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMember.objects.filter(
             user = self.request.user,
             group__slug = self.kwargs.get('slug')
            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request,'You Have left the group!')
        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
 <div class="container">
   {% block pregroup %}
   {% endblock %}
   {% block group_content %}
   {% endblock %}
   {% block postgroup %}
   {% endblock %}
 </div>
{% endblock%}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<h1> {{group.name}} </h1>
<h2> memebers: {{group.members.count}} </h2>
<div class="content">
  {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
      <span>Leave {{group.name}} </span>
    </a>
  {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
      <span>join {{group.name}} </span>
    </a>
  {% endif %}
</div>

{% endblock %}


{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count > 0 %}
    {% for post in group.posts.all %}
      {% include 'posts/_post.html' %}
    {% endfor %}
  {% else %}
   <h2> No Posts in group {{group.name}} yet!</h2>
  {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}
{% block group_content %}
  <h4>Create a new group!</h4>
  <form action="{% url 'groups:create'%}" method="post" id='groupForm'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="Create">
  </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block group_content %}
  <div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
          <h2>Welcome Back
          <a href="{% url 'posts:for_user' username=user.username %}">
            @{{user.username}}
          </a></h2>
        {% endif %}

        {% if user.is_authenticated %}
          <h2>Groups</h2>
          <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
            Create a new group <i class="fa fa-plus" aria-hidden="true"></i>
          </a>
        {% endif %}

    </div>
{% endblock %}
{% block pregroup %}
 <div class = "col-md-8">
    <div class="list-group">
      {% for group in object_list %}
      <div class="list-group-item">
        <a href="{% url 'groups:single' slug=group.slug %}">
     <h3 class="title list-group-item-heading">{{group.name}}</h3></a>

      <div class="list-group-item-text container-fluid">
        {{group.description_html|safe}}
        <div class="row">
            <div class="col-md-4">
              <span class="badge badge-success">{{group.members.count}}</span>
                member{{group.members.count.pluralize}}
            </div>
            <div class="col-md-4">
              <span class="badge badge-success">{{group.posts.count}}</span>
                post{{group.posts.count|pluralize}}
            </div>
        </div>
      </div>
</div>
      {% endfor %}
    </div>
  </div>
 </div>
{% endblock %}
</div>