accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',
    auth_views.LoginView.as_view(template_name ='accounts/login.html'),
    name='login'),

    path('logout/',
    auth_views.LogoutView.as_view(),
    name ='logout'),

    path('signup/',
    views.SignUp.as_view(),
    name='signup')
]

posts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings # new
from django.conf.urls.static import static # new

app_name = 'posts'


urlpatterns = [
	path('',views.PostList.as_view(),name='all'),
	path('new/',views.CreatePost.as_view(),name='create'),
	path('by/(?P<username>[-\w]+)/',views.UserPosts.as_view(),name='for_user'),
	path('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(),name='single'),
	path('delete/(?P<pk>\d+)/',views.DeletePost.as_view(),name='delete'),
	path('update/(?P<pk>\d+)/',views.UpdatePost.as_view(),name='update')

]


# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="{%static 'css/master.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Social</title>
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand " href="{% url 'home' %}">Star <span class="green">Social</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'posts:create' %}">Post</a>
              <a class="dropdown-item" href="{% url 'groups:all' %}">Groups</a>
              <a class="dropdown-item" href="{% url 'groups:create' %}">Create Group</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="#">Groups</a>
              <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
              {% endif %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>

      </div>
    </nav>
    <!-- end navbar -->
      {% block content %}

      {% endblock %}

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Hi this is a new social</h1>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are logged in</h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thank You</h1>
{% endblock %}