posts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings # new
from django.conf.urls.static import static # new

app_name = 'posts'


urlpatterns = [
	path('',views.PostList.as_view(),name='all'),
	path('new/',views.CreatePost.as_view(),name='create'),
	path('by/(?P<username>[-\w]+)/',views.UserPosts.as_view(),name='for_user'),
	path('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(),name='single'),
	path('delete/(?P<pk>\d+)/',views.DeletePost.as_view(),name='delete'),
	path('update/(?P<pk>\d+)/',views.UpdatePost.as_view(),name='update')

]


# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from django.contrib.auth import get_user_model
from django import template
from groups.models import Group
from uuid import uuid4
import os

User = get_user_model()

def path_and_rename(instance, filename):
    upload_to = 'posts'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class Post(models.Model):
	 user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
	 created_at = models.DateTimeField(auto_now=True)
	 message = models.TextField()
	 message_html = models.TextField(editable=False)
	 image = models.ImageField(upload_to=path_and_rename, null=True,blank=True)
	 group = models.ForeignKey(Group,related_name='posts',null=True,blank=False,on_delete=models.CASCADE)

	 def __str__(self):
	 	return self.message

	 def save(self,*args,**kwargs):
		 self.message_html = misaka.html(self.message)
		 super().save(*args,**kwargs)

	 def get_absolute_url(self):
		 return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})
		#pk is for a primary key

	 class Meta:
		 ordering = ['-created_at']

posts/forms.py
from django.forms import ModelForm
from groups.models import Group
from posts.models import Post
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class CreatePostForm(forms.ModelForm):
        class Meta:
            model = Post
            fields = ('message', 'group','image')

        def __init__(self, *args, **kwargs):
            # self.fields['user'] = User.id
            user = kwargs.pop('user', None)
            super(CreatePostForm, self).__init__(*args, **kwargs)

            # self.fields['group'].queryset = user.user_groups.all().values_list('name')
            self.fields['group'].queryset = Group.objects.filter(members = user)

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib.auth import get_user_model
from django.contrib import messages

User = get_user_model()

#hint: LoginRequiredMixin == @login_required
class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related=('user','group') #the fetched related data put in the context

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user= User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    select_related = ('user','group')
    template_name ='posts/post_form.html'
    form_class = forms.CreatePostForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,"Post Deleted")
        return super().delete(*args,**kwargs)

class UpdatePost(LoginRequiredMixin,generic.UpdateView):
    model = models.Post
    fields = ['message', 'group','image']

posts/templates/posts/_post.html
<br>

{% load staticfiles %}

<div class="jumbotron">
  <a href="{%url 'posts:for_user' username=post.user.username %}">
    <h3 class="display-4"><strong>{{post.user.username}}</strong></h3>
  </a>

  {% if post.image %}
    <img src="{{post.image.url}}" height="50px"> 
  {% else %}
  <p>No image To show </p>
  {% endif %}
  <p class="lead">{{post.message_html|safe}}</p>
  {% if request.user.is_authenticated  and request.user.username == post.user.username  %}

      <p class="lead">
        <a class="btn btn-danger" href="{%url 'posts:delete' pk=post.pk %}" role="button">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </a>

        <a class="btn btn-success" href="{%url 'posts:update' pk=post.pk %}" role="button">
          <i class="fa fa-edit" aria-hidden="true"></i>
        </a>

      </p>
  {% endif %}

</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
  <div class="contianer">
      {% block prepost %} {% endblock %}
      {% block post_content %} {% endblock %}
      {% block post_post %} {% endblock %}
  </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
  <h3>Are you sure you want to delete this post ?</h3>
  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>


  <form method="post">
      {% csrf_token %}
      <input type="submit" value="confirm delete" class="btn btn-danger btn-large">
      <a href="{% url 'posts:single' username=user.username pk=object.pk%}" class="btn btn-primary btn-large">Cancel</a>
  </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_content %}
  <div class="col-md-8">
      {% include "posts/_post.html" %}
  </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}
{% block post_content %}
{#<form id = 'postForm' action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">#}
<form id = 'postForm' method="post" enctype="multipart/form-data">
    {% csrf_token %}
{% bootstrap_form form  %}
    <input type="submit" class="btn btn-primary" value="Post">
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card" style="width: 18rem;">
        <div class="card-header">
          your groups
        </div>
        <ul class="list-group list-group-flush">
          {% for member_group in user.user_groups.all %}
            <li class="list-group-item">
              <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{member_group.group.name}}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
    <!-- <div class="card" style="width: 18rem;">
        <div class="card-header">
          All groups
        </div>
        <ul class="list-group list-group-flush">
          {% for other_group in get_other_groups %}
            <li class="list-group-item">
              <a href="{% url 'groups:single' slug=other_group.slug %}">
                {{other_groups.name}}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div> -->
  </div>
{% endblock %}

{% block post_content %}
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
  <div class="col-md-4">
      <h1>@{{post_user.username}}</h1>
  </div>
{% endblock %}

{% block post_content %}
<div class="col-md-4">
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}
</div>

{% endblock %}